version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12  # Use a proper Python 3.12 image
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install Python via pyenv (if needed)
          command: |
            pyenv install --skip-existing 3.12.1
            pyenv global 3.12.1
            python --version

      - run:
          name: Install uv and dependencies
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            uv pip install pytest pytest-cov mypy ruff coverage

      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/results.xml --cov=src --cov-report=xml --cov-report=html

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: htmlcov
          destination: test-coverage

workflows:
  version: 2
  test_pipeline:
    jobs:
      - test
