version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12  # Use a proper Python image
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install UV
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh

      - run:
          name: Create Virtual Environment
          command: |
            uv venv  # Creates a virtual environment

      - run:
          name: Install Dependencies
          command: |
            . .venv/bin/activate  # Activate the virtual environment
            uv pip install pytest pytest-cov mypy ruff coverage

      - run:
          name: Run Tests
          command: |
            . .venv/bin/activate  # Activate before running pytest
            pytest --junitxml=test-results/results.xml --cov=src --cov-report=xml --cov-report=html

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: htmlcov
          destination: test-coverage

workflows:
  version: 2
  test_pipeline:
    jobs:
      - test
